baseURL = "http://rifkifauzi.id/"
languageCode = "en-us"
title = "Rifki Fauzi"
theme = "cocoa"

[params]
  avatar = "https://yt3.ggpht.com/-JNih4JWK34Q/AAAAAAAAAAI/AAAAAAAAmt8/HfOLX-KEc94/s288-mo-c-c0xffffffff-rj-k-no/photo.jpg"
  selfintro = "Family guy, Software engineer, Coding instructor, Lifelong learner"
  github = "https://github.com/kubido"
  instagram = "https://instagram.com/kubid"
  author = "Rifki Fauzi"
  cachebuster = true
  forcehttps  = true

[[menu.main]]
name                   = "Latest"
weight                 = -110
identifier             = "latest"
url                    = "/"

[[menu.main]]
name                   = "Personal"
weight                 = -100
identifier             = "Personal"
url                    = "/tags/personal/"

[[menu.main]]
name                   = "Coding"
weight                 = -90
identifier             = "coding"
url                    = "/tags/coding/"

[[menu.main]]
name                   = "English"
weight                 = -80
identifier             = "english"
url                    = "/tags/english/"

[[menu.main]]
name                   = "Gallery"
weight                 = -70
identifier             = "gallery"
url                    = "/gallery/"
